const picks={"puns":[{Puns :" Are you african? because you are a’frican babe"},
{Puns :" Even though there aren’t any stars out tonight, you’re still shining like one"},
{Puns :" Are you a bank loan? Because you got my interest"},
{Puns :" Are you Franklin D Roosevelt because damn baby you a dime"},
{Puns :" Are you sure you’re not a parking ticket? Because you’ve got fine written all over you"},
{Puns :" Are you a time traveler? Cause I see you in my future!"},
{Puns :" Do you like star wars? Because yoda only one for me!"},
{Puns :" Are you mexican? Because you’re my juan and only!"},
{Puns :" Are you a 45 degree angle? Because you’re acute-y!"},
{Puns :" Do you have 11 protons? Because you’re sodium fine!"},
{Puns :" If you were a potato you’d be a sweet one."},
{Puns :" My doctor says i’m lacking Vitamin U"},
{Puns :" Are you a keyboard? Because you’re just my type."},
{Puns :" Are you the square root of -1 because you can’t be real"},
{Puns :" Are you French? because Eiffel for you."},
{Puns :" If I were to ask you out on a date, would your answer be the same as the answer to this question?"},
{Puns :" If I could rearrange the alphabet I would put U and I together."},
{Puns :" If I could rearrange the alphabet I would put U and I together."},
{Puns :" If beauty were time, you’d be eternity."},
{Puns :" Is your name Wi-fi? Because I'm really feeling a connection."},
{Puns :" If I were a cat I'd spend all 9 lives with you."},
{Puns :" If looks could kill, you'd be a weapon of mass destruction."},
{Puns :" Do you have a name, or can I call you mine?"},
{Puns :" Did you swallow magnets? Cause you're attractive."},
{Puns :" Are you Australian? Because you meet all of my koala-fications."},
{Puns :" If you were a vegetable you'd be a cutecumber."},
{Puns :" Can I take a picture of you so santa knows what I want for christmas?"},
{Puns :" Do you believe in love at first sight or should I walk past again?"},
{Puns :" Did your licence get suspended for driving all these guys crazy?"},
{Puns :" Is your face Mcdonalds? Cause im lovin it!"},
{Puns :" You so lovely, you make me wanna go out and get a job"},
{Puns :" Are you a Disney princess? Cause you’re cinderHella fine!"},
{Puns :" Are you from Russia? ‘Cause you’re russian my heart rate!"},
{Puns :" Is your name Ariel? Cause we Mermaid for each other!"},
{Puns :" Kanye feel the love tonight?"},
{Puns :" You know what’s beautiful? Read the first word."},
{Puns :" Can I follow you? Cause my mom told me to follow my dreams"},
{Puns :" Aside from being sexy, what do you do for a living?"},
{Puns :" I’m no organ donor but I’d be happy to give you my heart."},
{Puns :" You look familiar, didn’t we take a class together? I could’ve sworn we had chemistry. "},
{Puns :" I used to be a Gambler, but then I realized that all I needed was the Queen of my Heart"}]
}
const facts={"facts":[{Facts :"Architecture Was Once an Olympic Sport"},
{Facts :"Frank Lloyd Wright's Son Invented Lincoln Logs"},
{Facts :"LEGO Used to Make Special Bricks for Architects"},
{Facts :"Maya Lin Is the Niece of One of the Most Famous Female Architects in Modern Chinese History"},
{Facts :"The Cooper Union Foundation Building in NYC Included an Elevator Shaft, Even Though Modern Elevators Hadn't Been Invented Yet"},
{Facts :"The Sims Was Originally Designed as an Architecture Simulator"},
{Facts :"The Empire State Building Generates More Revenue from its Observation Decks than from its 85 Floors of Office Space"},
{Facts :"The City of Cincinnati, Ohio Has an Abandoned Subway System Which Was Never Used"},
{Facts :"The Supervisor of the Ouija Board Company Fell to His Death From the Roof of a Factory that the Board Told Him to Build"},
{Facts :"More Time Passed Between the Start and End of Construction on the Great Wall of China than Between the Start of Christianity and Today"},
{Facts :"Multi-unit apartment buildings in Rome were referred to as 'insulae'. "},
{Facts :"England's Stonehenge is 1500 years older than Rome's Colosseum. "},
{Facts :"At Plaza de Colón in Madrid, Spain, there is a twin building that is known locally as El Enchufe or The Plug for it is said to resemble a giant electrical plug. Torres de Colón has been an icon of Madrid’s skyline since it went up in 1976. Torres de Colón was built from top to bottom."}
]}
const quotes={"quotes":[{Quotes :"When you reach the end of your rope, tie a knot in it and hang on."},
{Quotes :" There is no charm equal to tenderness of heart. "},
{Quotes :" Learning never exhausts the mind."},
{Quotes :" The only journey is the one within."},
{Quotes :" No act of kindness, no matter how small, is ever wasted."},
{Quotes :" The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart."},
{Quotes :" Keep love in your heart. A life without it is like a sunless garden when the flowers are dead."},
{Quotes :" Don't judge each day by the harvest you reap but by the seeds that you plant."},
{Quotes :" Do all things with love."},
{Quotes :" Do not go where the path may lead, go instead where there is no path and leave a trail."},
{Quotes :" Love isn't something you find. Love is something that finds you."},
{Quotes :" In three words I can sum up everything I've learned about life: it goes on."},
{Quotes :" The future belongs to those who believe in the beauty of their dreams."},
{Quotes :" Happiness resides not in possessions, and not in gold, happiness dwells in the soul."},
{Quotes :" Everything has beauty, but not everyone sees it."},
{Quotes :" Life isn't about finding yourself. Life is about creating yourself."},
{Quotes :" Life is not a problem to be solved, but a reality to be experienced."},
{Quotes :" A single rose can be my garden... a single friend, my world."},
{Quotes :" If opportunity doesn't knock, build a door."},
{Quotes :" Let us be grateful to people who make us happy, they are the charming gardeners who make our souls blossom."},
{Quotes :" Not all those who wander are lost."},
{Quotes :" Keep your face always toward the sunshine - and shadows will fall behind you."},
{Quotes :" If you cannot do great things, do small things in a great way."},
]}
const puns={"puns":[{"Pun":"The person who invented the door knock won the No-bell prize."},
{"Pun":"I couldn't work out how to fasten my seatbelt. Then it clicked."},
{"Pun":"Never trust atoms, they make up everything."},
{"Pun":"Singing in the shower is all fun and games until you get shampoo in your mouth, then it just becomes a soap opera."},
{"Pun":"I can't believe I got fired from the calendar factory. All I did was take a day off."},
{"Pun":"To the guy who invented Zero: Thanks for nothing!"},
{"Pun":"Enough with the cripple jokes!...I just can't stand them."},
{"Pun":"I've accidentally swallowed some Scrabble tiles. My next crap could spell disaster."},
{"Pun":"There are plenty of fish in the sea but until I catch one I'm just stuck here holding my rod..."},
{"Pun":"How does Moses make his tea? Hebrews it."},
{"Pun":"Did you hear about the guy who got hit in the head with a can of soda? He was lucky it was a soft drink."},
{"Pun":"When William joined the army he disliked the phrase 'fire at will'."},
{"Pun":"There was a sign on the lawn at a drug re-hab center that said 'Keep off the Grass'."},
{"Pun":"I wondered why the baseball was getting bigger. Then it hit me."},
{"Pun":"I can hear music coming out of my printer. I think the paper's jammin' again."},
{"Pun":"I have a few jokes about unemployed people, but it doesn't matter none of them work"},
{"Pun":"Want to hear a construction joke? I'm working on it"},
{"Pun":"I always take a second pair of pants when I go golfing... in case I get a hole in one."},
{"Pun":"I couldn't quite remember how to throw a boomerang, but eventually it came back to me."},
{"Pun":"So i've decided that my wifi will be my valentine. IDK, we just have this connection."},
{"Pun":"I was going to tell a Mexican joke, but that's just crossing the border!"},
{"Pun":"A prisoner's favorite punctuation mark is the period. It marks the end of his sentence."},
{"Pun":"what do you call a fake noodle? an IMPASTA!"},
{"Pun":"I'm trying to think of a Miley Cyrus joke but its not twerking."},
{"Pun":"I'm going to stand outside, so if anyone asks I'm outstanding."},
{"Pun":"I used to go fishing with Skrillex, but they kept dropping the bass."},
{"Pun":"I just realised that I haven't done the hokey pokey in over 10 years. I guess when you get older, you just forget what it's all about."},
{"Pun":"2 antennas met on a roof and got married. The wedding was ok, but the reception was incredible."},
{"Pun":"A book just fell on my head. I've only got my shelf to blame."},
{"Pun":"This girl said she recognized me from the vegetarian club"},
{"Pun":"I dropped my burger on the floor. Now it's ground beef."},
{"Pun":"I used to have a fear of hurdles, but I got over it."},
{"Pun":"The outcome of war does not prove who is right, but only who is left."},
{"Pun":"Darth Vader once made cookies, but they were a little on the dark side."},
{"Pun":"The store keeps calling me to come back and buy more furniture... but all i really wanted was a one night stand."},
{"Pun":"This girl said she recognized me from the vegetarian club, but I'd never met herbivore."},
{"Pun":"Police arrested two kids yesterday, one was drinking battery acid, the other was eating fireworks. They charged one and let the other one off..."},
{"Pun":"No more Harry Potter jokes guys, I'm Sirius."},
{"Pun":"It was hard getting over my addiction to hokey pokey, but I've turned myself around."},
{"Pun":"Why can't a bike stand on it's own? Because it is two tired."},
{"Pun":"It takes a lot of balls to golf the way I do."},
{"Pun":"Why did everyone want to hang out with the mushroom? Because he was a fungi."},
{"Pun":"How much does a hipster weigh? An instagram"},
{"Pun":"I used to be addicted to soap, but I'm clean now."},
{"Pun":"When life gives you melons, you’re probably dyslexic."},
{"Pun":"Stop with the blind jokes...I dont see their point"},
{"Pun":"If Apple made a car, would it have Windows?"},
{"Pun":"Need an ark to save two of every animal? I noah guy."},
{"Pun":"The scare crow got promoted to the manager at a supermarket, because he was outstanding in his field"},
{"Pun":"What is the difference between a nicely dressed man on a tricycle and a poorly dressed man on a bicycle? A tire."},
{"Pun":"What do you do with a sick chemist? If you can't helium, and you can't curium, you might as well barium."},
{"Pun":"I'm reading a book about anti-gravity. It's impossible to put down."},
{"Pun":"To write with a broken pencil is pointless."},
{"Pun":"Where do TVs go on vacation? To remote islands!"},
{"Pun":"I was going to tell a midget joke, but it's too short."},
{"Pun":"Jokes about German sausage are the wurst."},
{"Pun":"How do you organize a space party? You planet."},
{"Pun":"Sleeping comes so naturally to me, I could do it with my eyes closed."},
{"Pun":"I'm glad I know sign language, it's pretty handy."},
{"Pun":"Atheism is a non-prophet organization."},
{"Pun":"Velcro - what a rip-off!"},
{"Pun":"They should make a Minecraft movie, it would be a blockbuster."},
{"Pun":"I don't trust people with graph paper. They're always plotting something"},
{"Pun":"I had a friend who was addicted to brake fluid. He says he can stop anytime."},
{"Pun":"They told me I had Type A blood, but it was a Type O."},
{"Pun":"I went to to the shop to buy 8 sprites i came home and realised I'd picked 7Up"},
{"Pun":"Why are iPhone chargers not called Apple Juice?"},
{"Pun":"There was an explosion at a pie factory, 3.14 people died."},
{"Pun":"A man drove his expensive car into a tree and found out how a Mercedes bends"},
{"Pun":"I'm glad I know sign language, it's pretty handy."},
{"Pun":"The experienced carpenter really nailed it, but the new guy screwed everything up."},
{"Pun":"I didn't like my beard at first but then it grew on me."},
{"Pun":"Smaller babies may be delivered by stork but the heavier ones need a crane."},
{"Pun":"What's the definition of a will? (It's a dead giveaway)."},
{"Pun":"I was going to look for my missing watch, but I could never find the time."},
{"Pun":"I usually take steps to avoid elevators."},
{"Pun":"Did you hear about the guy whose whole left side was cut off? He's all right now."},
{"Pun":"It's not that the man did not know how to juggle, he just didn't have the balls to do it."},
{"Pun":"I used to be a banker but I lost interest"},
{"Pun":"I don't trust these stairs because they're always up to something."},
{"Pun":"My friend's bakery burned down last night. Now his business is toast."},
{"Pun":"Don't trust people that do acupuncture, they're back stabbers."},
{"Pun":"The man who survived mustard gas and pepper spray is now a seasoned veteran."},
{"Pun":"Police were called to a daycare where a three-year-old was resisting a rest."},
{"Pun":"Atheism is a non-prophet organization."},
{"Pun":"When Peter Pan punches, they Neverland"},
{"Pun":"The shoemaker did not deny his apprentice anything he needed. He gave his awl."},
{"Pun":"I did a theatrical performance about puns. Really it was just a play on words."},
{"Pun":"Show me a piano falling down a mineshaft and I'll show you A-flat minor."},
{"Pun":"Have you ever tried to eat a clock? It's very time consuming."},
{"Pun":"There was once a cross-eyed teacher who couldn't control his pupils."},
{"Pun":"A new type of broom came out, it is sweeping the nation."},
{"Pun":"I relish the fact that you've mustard the strength to ketchup to me."},
{"Pun":"The roundest knight at king Arthur's round table was Sir Cumference."},
{"Pun":"I knew a woman who owned a taser, man was she stunning!"},
{"Pun":"What did the grape say when it got stepped on? Nothing - but it let out a little whine."},
{"Pun":"It was an emotional wedding. Even the cake was in tiers."},
{"Pun":"When a clock is hungry it goes back four seconds."},
{"Pun":"The dead batteries were given out free of charge."}]}
export {picks,puns,facts,quotes}