const puns={"puns":[{Puns :" Are you african? because you are a’frican babe"},
{Puns :" Even though there aren’t any stars out tonight, you’re still shining like one"},
{Puns :" Are you a bank loan? Because you got my interest"},
{Puns :" Are you Franklin D Roosevelt because damn baby you a dime"},
{Puns :" Are you sure you’re not a parking ticket? Because you’ve got fine written all over you"},
{Puns :" Are you a time traveler? Cause I see you in my future!"},
{Puns :" Do you like star wars? Because yoda only one for me!"},
{Puns :" Are you mexican? Because you’re my juan and only!"},
{Puns :" Are you a 45 degree angle? Because you’re acute-y!"},
{Puns :" Do you have 11 protons? Because you’re sodium fine!"},
{Puns :" If you were a potato you’d be a sweet one."},
{Puns :" My doctor says i’m lacking Vitamin U"},
{Puns :" Are you a keyboard? Because you’re just my type."},
{Puns :" Are you the square root of -1 because you can’t be real"},
{Puns :" Are you French? because Eiffel for you."},
{Puns :" If I were to ask you out on a date, would your answer be the same as the answer to this question?"},
{Puns :" If I could rearrange the alphabet I would put U and I together."},
{Puns :" If I could rearrange the alphabet I would put U and I together."},
{Puns :" If beauty were time, you’d be eternity."},
{Puns :" Is your name Wi-fi? Because I'm really feeling a connection."},
{Puns :" If I were a cat I'd spend all 9 lives with you."},
{Puns :" If looks could kill, you'd be a weapon of mass destruction."},
{Puns :" Do you have a name, or can I call you mine?"},
{Puns :" Did you swallow magnets? Cause you're attractive."},
{Puns :" Are you Australian? Because you meet all of my koala-fications."},
{Puns :" If you were a vegetable you'd be a cutecumber."},
{Puns :" Can I take a picture of you so santa knows what I want for christmas?"},
{Puns :" Do you believe in love at first sight or should I walk past again?"},
{Puns :" Did your licence get suspended for driving all these guys crazy?"},
{Puns :" Is your face Mcdonalds? Cause im lovin it!"},
{Puns :" You so lovely, you make me wanna go out and get a job"},
{Puns :" Are you a Disney princess? Cause you’re cinderHella fine!"},
{Puns :" Are you from Russia? ‘Cause you’re russian my heart rate!"},
{Puns :" Is your name Ariel? Cause we Mermaid for each other!"},
{Puns :" Kanye feel the love tonight?"},
{Puns :" You know what’s beautiful? Read the first word."},
{Puns :" Can I follow you? Cause my mom told me to follow my dreams"},
{Puns :" Aside from being sexy, what do you do for a living?"},
{Puns :" I’m no organ donor but I’d be happy to give you my heart."},
{Puns :" You look familiar, didn’t we take a class together? I could’ve sworn we had chemistry. "},
{Puns :" I used to be a Gambler, but then I realized that all I needed was the Queen of my Heart"}]
}

export {puns}